### ISSUE TITLE
Advanced Authentication issue with Android on Chromebook

### ISSUE THREAD

**Issue by donpwilson** [CloudRail/cloudrail-si-android-sdk#117]
My app logs in to Google Drive, OneDrive, Dropbox and Box. All works well except Google Drive and Dropbox on my Chromebook (Acer R.11 CB5 - 132T). At some stage in the past, I think they also worked but I'm not exactly sure when.

On debugging I isolated the issue. This is that the Intent that is passed back from the browser to the app has null Categories. It has the correct Data in it because, when I comment out the text for whether Categories include BROWSABLE, the login proceeds correctly. Categories is only null on the Chromebook, which is running Android 7.1.1. On my other test devices, which include the emulator running 7.1.1, the intent correctly includes BROWSABLE. 

I have tested with the app both enabling and disabling resizing on the Chromebook with the same result.

I have trawled through the Chromebook's settings and couldn't find anything that might be set incorrectly to cause this issue.

To see the effect, I deleted the DEFAULT and BROWSABLE Categories from the Intent filter. In this case the browser gives the error message "Google Chrome OS can't open this page" and I can't log in.

Any thoughts? Is it "safe" to remove the test for BROWSABLE from my code or  might it lead to your authentication code crashing? Have you done any testing on a Chromebook?

**Comment by PatrickStoklasa** [comment]
Actually, I have had the same behavior on some of the later Android versions I think. I have not tested this on a Chromebook yet so not sure about this but I believe removing the check itself should not cause any issue if you are not handling other Intents in this Activity. The reason we inserted this check was just to make sure that we don't forward an Intent that is not a redirect.

There should be two possible ways to go about this: Either you just remove the check which should be safe when you don't have multiple filters for the same activity or instead of testing the category you could investigate the data property of the Intent and compare it to the expected redirect URI.

**Comment by donpwilson** [comment]
Thanks for the prompt response.

This is the only intent-filter in my app other than the main Launcher so I'll just remove the check.
