### ISSUE TITLE
OneDrive Permissions

### ISSUE THREAD

**Issue by donpwilson** [CloudRail/cloudrail-si-android-sdk#27]
When you first login to  Cloud Storage, you need to accept the application permissions. For OneDrive (but not Dropbox or Box) they are currently rather more than requirements and are positively scary for a user - see screenshot. Could these be reduced to just OneDrive files.

![screenshot_20160802-161527](https://cloud.githubusercontent.com/assets/8239187/17334514/6848b5e4-58ce-11e6-974a-f9679bf68425.png)

**Comment by PatrickStoklasa** [comment]
Apparently, all of the scopes are required. The first and the last one are fine, i guess you would agree on that. The second one is needed because our interface also returns the email address of the user if requested. And the third one allows us to automatically refresh the token we obtained during the authentication process which is a huge benefit for the user as well since he doesn't have to login again every time he launches the application. 

I get your point though! Permissions are always a tricky thing but even when it would be enough for you to just have the last one, for others it might not be sufficient. So in this case there is nothing we can do about it.

**Comment by donpwilson** [comment]
Please could you clarify the email address point. The OneDrive service is only implemented with the Cloud Storage interface. I can't see where the email address can be retrieved using this interface.

**Comment by PatrickStoklasa** [comment]
The CloudStorage interface has a method called 'getUserLogin' which returns some sort of unique identifier / username for the user if needed and in most of the CloudStorage services this is just the email address.

**Comment by donpwilson** [comment]
Thanks
