### ISSUE TITLE
getModifiedAt() for Box returning null

### ISSUE THREAD

**Issue by donpwilson** [CloudRail/cloudrail-si-android-sdk#31]
The method getReturningAt() for the Box service is returning null for files. It's working fine for Dropbox and OneDrive. Also, the other file metadata is present for Box.

**Comment by FlorianWendel** [comment]
Thanks for your report!

This seems to occur for the CloudMetaData objects for Box retrieved through getChildren() due to a bug. 
getMetadata() on the same file will actually give you complete metadata. 
We'll fix it and tell you once it's done, if time is of the essence you could also work around it by just taking the path from the incomplete metadata and invoke getMetadata with it for the time being. We should be able to get it done today though.

**Comment by donpwilson** [comment]
I can wait. There's still a lot I need to do to complete my implementation of CloudRail.

**Comment by PatrickStoklasa** [comment]
The new version is out now. The issue should be solved.

**Comment by donpwilson** [comment]
This is working now, thanks.
