### ISSUE TITLE
Github profile returns null for fullName, email

### ISSUE THREAD

**Issue by donjerick** [CloudRail/cloudrail-si-android-sdk#37]
Hi, may I ask why only in Github profile I am not getting values for fullName, email, dob, locale? Also, how do I add scope for the request on respective social provider? Most providers requires additional permission to access user's email address. And just to confirm does profile.saveAsString(); returns the access token from provider? If not, is there a way I can retrieve the access token using CloudRails SDK? Thank you!

**Comment by FlorianWendel** [comment]
Hi,

not every social network stores all the information we define in the Profile interface and not every user provides all of it to the network. E.g., users simply cannot set their date of birth on GitHub and not everyone will have their email address public.
Right now we request permissions for all the user's information, but we'll discuss adding a more fine grained scoping.
profile.saveAsString() returns a user's credentials as a JSON string, the access token is contained in it for all services using OAuth 2.0 but also other information like refresh token etc. You can parse the string and get the access token in a service specific manner since the string's format is not unified among all services (it can't be since e.g. Twitter with OAuth 1.0 has other credentials).

**Comment by donjerick** [comment]
Thanks for the quick response @FlorianWendel! 

Though I believe fullName should always have value to address properly the user. 
Also can you kindly point me to a reference on how to parse the string from profile.saveAsString() to get the access token, expiry, etc.?

**Comment by FlorianWendel** [comment]
http://stackoverflow.com/a/9606629/5599603 explains it quite nicely, you can skip the "Get your JSON" part.

**Comment by donjerick** [comment]
Saw it. Thanks for that! Managed to get the accessToken from the JSON string. 
I'll just call on GitHub API to get user details(name, email, etc.) using the accessToken. 

Great job @FlorianWendel!
