### ISSUE TITLE
Support shared folders for Dropbox

### ISSUE THREAD

**Issue by PhilippC** [CloudRail/cloudrail-si-android-sdk#40]
Dropbox has introduced sharing of folders:
https://www.dropbox.com/developers/documentation/http/documentation#sharing-share_folder

Could you please support this through the Dropbox class? I understand that this is not possible to include in the CloudStorage interface, but having it available in the concrete implementation Dropbox would be very beneficial anyways. Apps can then offer features based on the actual cloud storage provider.

**Comment by FlorianWendel** [comment]
Hi there,

we've been considering adding popular specific functions to single Services
for a while and your suggestion seems like another good candidate. It will
be a bit more complicated than a simple API call due to the synchronous and
asynchronous case depending on the folder's size though. I've put it on our
list, we'll attack it in parallel to the facilitated authentication feature
when the provider's app is already present.

**Comment by FlorianWendel** [comment]
Check out our newest functionality (https://documentation.cloudrail.com/android/android/Usage#advanced-request), you should be able to implement your requested feature with it.
