### ISSUE TITLE
Questions re latest improvements to CloudStorage SDK

### ISSUE THREAD

**Issue by donpwilson** [CloudRail/cloudrail-si-android-sdk#42]
1. Thumbnail documentation states that thumbnail is returned "if there is one available". Is a thumbnail returned whenever the file is a valid photo or are there more conditions that need to be satisfied?
2. Does the Thumbnail InputStream include MetaData in the way that the InputStream for a full sized photo does? If so, which items - all that are included in the full photo?
3. Do you have any plans in the short term to include the date photo taken and orientation in the metadata returned? It's difficult to take advantage of width and height without, in particular, the date photo taken also being included. I would still need to download the full InputStream to get this info.

**Comment by PatrickStoklasa** [comment]
1. We basically always return a thumbnail if the service provides us with one. Usually this means that for all the common images you can be very sure to get one. The only exception is, if you just uploaded an image and try to get a thumbnail right afterwards cause it might need some time to be generated on their server. Furthermore, some services also provide thumbnails for folders others return a placeholder thumbnail while they generate the real one. 

2. We just pass through the stream that the service returns, so whatever metadata it returns will also be included. I haven't tried it out myself yet so i can't tell you more so far.

3. The reason why we didn't include it so far is that not all of the services provide this kind of metadata. If it is crucial for you we might be able to add it with the next release since this shouldn't be a lot of effort.

**Comment by donpwilson** [comment]
I've had a look at thumbnails and they do not appear to include metadata so, unfortunately, this does not provide a workaround.

The date photo taken is not "crucial" because I have a workaround. That said, having it available as metadata would provide a significant performance boost because I would not need to download every photo at the start to get this information. My apps use this info to enable users to sort photos into this order because it is the natural order in which to display photos. It is beneficial to be able to sort before downloading the photos required given that photos are often 1Mb+ in size. So "very useful".

The other metadata I use is orientation - needed if the photo needs to be rotated, and description - used for display purposes. I can wait until the full photo needs to be downloaded to get this info.

**Comment by donpwilson** [comment]
Is there anything you can say yet about including "date taken" in image metadata?

**Comment by PatrickStoklasa** [comment]
The issue with that is that none of the services except for Google Drive provides this information in their image metadata. So in order to get the data we would still need to download the full images for all but Google Drive. Because of that, it is not a top priority improvement at the moment since it only provides limited value.

**Comment by donpwilson** [comment]
Noted and accepted
