### ISSUE TITLE
getImageMetaData returning null

### ISSUE THREAD

**Issue by donpwilson** [CloudRail/cloudrail-si-android-sdk#43]
getImageMetaData returns null when obtaining CloudMetaData through service.getChildren, at least for OneDrive and maybe Dropbox.

I tried testing using service.getMetaData. OneDrive returned the correct values for width but Box returned null. I haven't yet established whether this was from getImageMetaData or getWidth.

I'll continue checking (and can give more diagnostics) when I next get a chance but hopefully you'll be able to pinpoint the issue.

**Comment by PatrickStoklasa** [comment]
The reason why it returns null for Box in all the cases is that Box doesn't return image metadata like all the other services do. They just don't seem to include it into their metadata. I will check out the issue with getChildren and let you know as soon as possible.

**Comment by donpwilson** [comment]
OK, I'll test for null. Can I suggest that you indicate that it might be null in Javadoc. Also, indicate the limitations for Box somewhere (I'm sure there are and will be various limitations for various services) so that developers know in advance how far Cloudrail can meet their needs

**Comment by PatrickStoklasa** [comment]
I appreciate your feedback and I think it makes a lot of sense. We planned to do some more around documentation anyway since we will probably continue to implement features that are not supported throughout all services. In order for that to be clear to all the developers we definitely need to improve the documentation and highlight what is possible with which services.

Concerning the issue: we found the bug in OneDrive and Google Drive and the upcoming version will contain the fix.

**Comment by donpwilson** [comment]
I've received the notification that the bug is fixed and I'm testing it.

The notification shows me the changes that affect how my apps currently use CloudRail. Is there a log I can access which shows all the changes in each upgrade so that I can see if there is anything I’d like to add? I had a look but couldn’t find one.

**Comment by FlorianWendel** [comment]
Have a look at https://github.com/CloudRail/cloudrail-si-android-sdk/blob/master/changelog.txt

**Comment by donpwilson** [comment]
Thanks. Exactly what I was looking for. Apologies for not spotting it myself

 

Don
