### ISSUE TITLE
CloudRail for Android is UNUSABLE

### ISSUE THREAD

**Issue by foobnix** [CloudRail/cloudrail-si-android-sdk#46]
Hello CloudRail Team.

I am Android developer and decide to add you library to my Android Application. (more then 12 million downloads)

The idea is Excellent to have many services in one place but Realization is VERY BAD and has security problems.

1) Google Drive 
Why do you open the Browser if the user on Android is signed in the system and can choose account in the dialog?

2) Dropbox
Why do you use internal browser?
I wish to use Google Chrome where my user already signed.

3) Using internal browser is NOT Safe, I don't see the URL of the service maybe it's Drobox but it can be hacked "Dropbox" with the same design and third-part service can stole my
password.
It's  not safe to use Internal browser, no one popular android app can't use your CloudRail with this functionality.

4) If I have installed Dropbox application I don't need to login again in browser, you can take outh key from this application.

5) If i don't grant permissions you internal browser not handle this scenario.

I wish you to fix this critical bugs for android app.

Thank you very much.

**Comment by FlorianWendel** [comment]
Hello Ivan,

thank you for voicing your concerns. 
I disagree with your claims that our Android SDK is insecure or "VERY BAD".
Let me address some of your points:

1 and 4: This suggestion has been discussed before, have a look at https://github.com/CloudRail/cloudrail-si-android-sdk/issues/33

2: We use the internal browser to have a more controlled environment for the website to open since the WebView is part of the Android API. No matter which browsers the user happens to have installed, we know that the WebView will reliably display the authorization pages.

3: I do not see why using the Android WebView would be unsafe. It is the CloudRail SDK that tells the WebView which URL to load. No third party can manipulate that process unless of course the user's phone has already been compromised. But in this case the doors are wide open anyway, no matter how we open the website.

5: You are right, if the user logs in to their account and then refuses access they'll see a broken website (which they can close and continue). This is not an ideal experience and I'll put this on our TODO list.

I'm happy to set up a Skype call with you if you wish to discuss any of this in detail.

**Comment by foobnix** [comment]
3: I do not see why using the Android WebView would be unsafe. 
Imagine you have download some app from the market. How do you know what SDKs does it used.
Some app show you in the internal webview page similar to Dropbox or similar to Gmail and ask you input the email and the password. 
How can you trust this app and how do you know you see real dropbox and not fake dropbox?

**Comment by FlorianWendel** [comment]
Just to be clear, we're talking about the scenario where a user does not trust the app they are using?

**Comment by foobnix** [comment]
If we talk about safety user need to know or to see the URL of the authorization page where he input this email and password. And he need to trust to the browser application.

**Comment by foobnix** [comment]
The idea of OAuth authorization to trust the OAuth providers and not give the password to user app. In you case with current Android implementation you can't guaranty the app can't have access to the password.

**Comment by FlorianWendel** [comment]
I understand what you're saying. We'll implement an alternative authentication approach to be used by apps that are not trusted by their users. Thanks for pointing this out. I still don't think that this makes the library generally unusable. When users trust the app's developer a WebView is just fine, but yes, in other cases and in the spirit of OAuth an external browser with visible SSL validation and visible URL should be preferred.

**Comment by foobnix** [comment]
Yes the library can be used in pet projects at this moment but can't in real.
I hope you will implement possibility for authentication in external browser and in offline app for this OAuth provider.
Then I will buy the license and will use you library :)
PS. User can use trusted or untrusted app no matter but he should trust for OAuth authentication process.

**Comment by PatrickStoklasa** [comment]
The latest release contains the "advanced" authentication in addition to the simple version. A sample can be found [here](https://github.com/CloudRail/cloudrail-si-android-sdk/tree/master/ExampleProjects/advanced_authentication). Let us know if this is the way you would expect it to work or if we missed anything.

Concerning the login with the provider apps, this was briefly discussed in this issue #33. So far, there is no "easy" way to integrate it into our SDK since it still requires the developer to do some additional configuration which is also mentioned in the above issue. However, you could acquire an access token from the provider apps and load it into our SDK which will make it skip the usual authentication process. If you would be open to use this workaround we can of course provide you with some code snippets that should make it easier unless you already have experience in that regard.
