### ISSUE TITLE
Download functionality not working

### ISSUE THREAD

**Issue by shailchokshi** [CloudRail/cloudrail-si-android-sdk#48]
Hi, I tried to use the download functionality. It gives the toast as file is downloaded. But I am unable to find the file in my downloads folder on my external storage.. Could anyone please comment or suggest.

**Comment by FlorianWendel** [comment]
Are you talking about the example application for cloud storage?

Am 11.11.2016 21:00 schrieb "shailchokshi" <notifications@github.com>:

**Comment by shailchokshi** [comment]
Yes Wendel

**Comment by PatrickStoklasa** [comment]
Does this issue occur for all of the services or only for a specific service? Which device are you using? Which Android version does your device run?

**Comment by shailchokshi** [comment]
Hi,
This happens for all the services. We are using Nexus 6 Android version 6.0
API 23

**Comment by PatrickStoklasa** [comment]
Ok, i think this explains it. I believe i know what the issue is. I will update the sample and see if that solves the issue. As soon as that is done i will come back to you.

**Comment by shailchokshi** [comment]
Thanks a ton.. This helped me a lot to understand the functionality of
Android as a beginner..😃

Regards,
Shail

**Comment by pm777** [comment]
I am also facing the same issue.
please help me out as soon as possible.

**Comment by PatrickStoklasa** [comment]
I just updated the File Viewer sample which should also run on Android 6. The reason why it wasn't working is that Android changed the way permissions are handled for the application. Prior to Android 6, it was enough to just specify the permissions an application needed in the manifest file. Starting from Android 6, in addition to declaring the permissions in your manifest, you also need to ask the user for granting you those rights during runtime. Since the standard Android API for doing this is not very pretty, we included an open source library which makes that job rather easy. If you are interested, just check out the new code. I also included a link to the library in a comment. If you still have issues, just let me know.
