### ISSUE TITLE
Callback when upload finished

### ISSUE THREAD

**Issue by jlelse** [CloudRail/cloudrail-si-android-sdk#5]
Could you add something like a callback feature, so that it's possible to check when the upload is finished and to retrieve whether the request was successful or not?

**Comment by FlorianWendel** [comment]
We tried to keep the interface in line with Java's common practices. We recommend that the calls, since they involve network operations, are executed in separate threads and thus e.g. the upload is finished once the call returns. You can then also be sure that it was successful, else an exception would have been thrown.
