### ISSUE TITLE
Twitter getEmail() returns null

### ISSUE THREAD

**Issue by VladimirDimovSBND** [CloudRail/cloudrail-si-android-sdk#50]
Hi there,
I try to get Twitter email after successful login but it always returns null. This applies on my twitter application (I make sure "Request email addresses from users" is checked) and on the sample application in this repository.

Regards.

**Comment by FlorianWendel** [comment]
Hi there,

at the moment we do not support getting email addresses from Twitter accounts.
I'll discuss adding this feature with the team.

On a side note, as described in our documentation, most of the methods on the services implementing Profile (like Twitter) can return null due to either

* the service not supporting the retrieval of the information
* the user not having set this information
* the user keeping the information private

This means that you should handle the case where e.g. getEmail returns null either way, if only because the address might not be set or hidden.
