### ISSUE TITLE
No progress indication during upload()?

### ISSUE THREAD

**Issue by wikirsch** [CloudRail/cloudrail-si-android-sdk#53]
Hi,
since upload of larg files might need some time, a progress indication (e.g. a progress dialog or progress bar) should be available to give feedback to user that the program is still alive (and furthermore how much work is already done and whats left to do). As far as I can see upload() currently does not support implementing some kind of progress indicator (e.g. by means of a callback).

**Comment by FlorianWendel** [comment]
You are right, progress indication is not currently supported. I'll put it on our list of potential new features.

**Comment by FlorianWendel** [comment]
I know that this is an old thread but since some people might still wonder about progress indications on upload and download: Both methods work with InputStreams and those can be encapsulated to get progress reports. So my statement above wasn't actually 100% true. An example of how this is implemented can e.g. be found in the Box SDK's source: 

https://github.com/box/box-java-sdk/blob/master/src/main/java/com/box/sdk/ProgressInputStream.java

The key idea is to encapsulate the InputStream that is uploaded with a ProgressInputStream before passing it to the upload method which consumes it. During the execution of the upload method progress should be emitted.

NB:
For the download case, you can encapsulate the InputStream that is returned from the download method (at this point the connection has been established but no data has been downloaded yet) with a ProgressInputStream before writing it to somewhere. During the reading of the encapsulated stream (e.g. when writing it to disk) data is downloaded and progress should be emitted.
