### ISSUE TITLE
Dropbox production denied

### ISSUE THREAD

**Issue by jaredrummler** [CloudRail/cloudrail-si-android-sdk#86]
I applied for production and was declined with the following response:

> Hi there,
> 
> Your production key request was declined for the following reason:Your app currently processes the OAuth app authorization flow inside a web view, instead of the system browser. In order to support the Google Sign In flow when signing in to authorize the Dropbox app, your app will need to be updated to use the system browser, in order to comply with Google's policy: https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html 
>
> If you believe your app shouldn't have been declined, or to resubmit your request, please email us at api-program@dropbox.com.Sincerely,
> 
> - The Dropbox Platform Team

Does CloudRail need to use Chrome Custom Tabs for Dropbox? What do I need to do to comply?

Thanks.

**Comment by PatrickStoklasa** [comment]
Hi Jared,

Due to the fact that Dropbox allows one to sign in with their Google account they are affected by the same changes in Google's authentication policies. The way to solve this would be to handle the authentication for Dropbox in a similar way then the one for GoogleDrive. 
Unfortunately Dropbox does not allow custom schemes (e.g. com.sample:/oauth2redirect) as a redirect uri. So you need to add an additional intent-filter for the redirect uri you are currently using for Dropbox and signal to the SDK that you want to use the advanced authentication for Dropbox as well.

**Comment by jaredrummler** [comment]
Hi Patrick,

Thanks for the response. I am now calling `useAdvancedAuthentication()` on dropbox and I added the `intent-filter` to the manifest. It is working, however, this seems to limit adding additional dropbox accounts because additional login attempts uses cookies with the default browser (#75). Do you have a solution for this? Thanks.

**Comment by PatrickStoklasa** [comment]
I remember the issue. There doesn't seem to be a way to do this the same way as with the old version. The only option would be to set a flag when redirecting to Dropbox that forces any user to login even if he is already logged in. I'm not sure if we want this as a general behavior but I will discuss it in the team and see if we can make it available somehow.

**Comment by PatrickStoklasa** [comment]
Hey Jared,

With the latest version of our SDK Dropbox generally asks the user to login, which should solve your issue.
