### ISSUE TITLE
Issue with Google Drive authentication

### ISSUE THREAD

**Issue by themelisx** [CloudRail/cloudrail-si-android-sdk#89]
I use the latest version of your library (Gradle: compile 'com.cloudrail:cloudrail-si-android:2.20.2')
I have read all your examples and docs, and all (dropbox, box, onedrive) works fine except Google Drive.
I got error 400 (invalid_request)
Invalid parameter value for redirect_uri: invalid scheme: com.themelisx.myshifts_pro:/auth
I tried with Google api key for android (as you say at one example) but I also tried with web api with redirect uri (as you say at another example/doc). What is finally that we must use for Google Drive?

rest of my code that may helps:
at manifest:

            android:name=".MainMenu"
            android:label="@string/app_name" 
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

            <intent-filter>
                <data android:scheme="com.themelisx.myshifts_pro" />
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
            </intent-filter>

file services.java (as is at your example)
with my own cloudrail api key, and all cloud api keys
and the code for Google Drive:

    private void initGoogleDrive() {
        googledrive.set(new GoogleDrive(context, GDRIVE_API_KEY, "", "com.themelisx.myshifts_pro:/auth", ""));
        ((GoogleDrive) googledrive.get()).useAdvancedAuthentication();
    }

at MainMenu.java:

    public class MainMenu extends Activity {

        @Override
        protected void onNewIntent(Intent intent) {
            if(intent.getCategories().contains("android.intent.category.BROWSABLE")) {
                CloudRail.setAuthenticationResponse(intent);
            }
            super.onNewIntent(intent);
        }

        private CloudStorage getService() {
             return Services.getInstance().getService(this.currentService);
        }

        @Override
        public void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            setContentView(R.layout.main_menu);
            Services.getInstance().prepare(this);
        }
    }

**Comment by PatrickStoklasa** [comment]
The redirect URI itself looks correct to me. So what is / are the guides you followed to obtain the correct credentials? The guide at https://cloudrail.com/integrations/services/GoogleDrive;platformId=Android in the 'API Keys' tab as well as the guide at https://blog.cloudrail.com/authenticating-google-drive/ describe the correct procedure as far as I'm aware. If there is any deprecated guide out there I would be glad to fix or remove it if it is no longer appropriate.

**Comment by themelisx** [comment]
I notice that at one sample you say to add [YourPackageName]:/oauth2redirect ( here: https://blog.cloudrail.com/authenticating-google-drive/ )
and at another sample you say com.cloudrail.example:/auth witch translated to me [YourPackageName]:/auth
At data android:scheme (in manifest) you just enter the package name.
Does it mater what is ? I cannot see anywhere used into the code.
Also at the guide here: https://blog.cloudrail.com/authenticating-google-drive/ you say to select android client. Not web. Only at web api keys asks for redirect uri.
Android OAuth 2.0 client IDs are contains only fingerprint SHA-1 and package name.

And finally why I should call login() for GoogleDrive and not for other cloud ? And when?
You suppose that you create a library that is all-in-one, with one interface.
If you know that Google Drive need advanced authentication, do it in your library when I create a new GoogleDrive. So if later google change something, you fix it internally and release a new library.
Why we need to do all this?

**Comment by PatrickStoklasa** [comment]
Generally, both redirect URIs work since the path (oauth2redirect or auth) does not matter at all when using a custom scheme (e.g. com.cloudrail.example). You can use any path you like. 
When creating OAuth credentials for Android in the Google Developer Console you can not set a redirect URI because it is implicitly done by Google. You can either use your package name or one of the weird values provided by Google.

You do not need to use login() for Google or any other service, the guide just uses the method for demonstration purposes. The login would still be triggered on the first method called.

Indeed we know that Google services require Advanced Authentication and we could also set it as a default for them. Let me explain why we didn't. Generally we would love to make the advanced authentication flow easier and reduce the additional effort for the developer but I have not seen a way to do that since we can not know the package name a developer, using our SDK, would choose and thus we can not register any Intent-Filter within the SDK. This means that the redirect needs to be captured by the developer and passed back to the SDK. If you can think of a way to handle this within the SDK I would be glad to implement it. And the reason we do not set the advanced authentication as a default is that we want the developer to know that there are additional steps required and a different way of authentication is used otherwise people might get confused about why the authentication does not behave in the same way. We also don't want to make the advanced authentication the standard since as you said it is more complicated then the normal one. I hope this gave you some insights into why we did what we did and I would be glad to get your feedback.

**Comment by themelisx** [comment]
1) do use different uri at your examples. It confuse us.
2) if uri not needed,... why you told us to provide it?
3) You say at guide that the uri can be our package name. So you know our package name and you can use it for advanced authentication. 
4) and finally, lets retrun to my issue. As you say everything at my code is correct. why I got "Invalid parameter value for redirect_uri: invalid scheme: com.themelisx.myshifts_pro:/auth" only at GoogleDrive?

**Comment by PatrickStoklasa** [comment]
I just did some tests and when I rename my package name to com.cloudrail.si.testapp_pro I get the same issue. Searching the web a bit it appears that _ is not a valid character for a url scheme https://stackoverflow.com/questions/9142309/may-url-scheme-contain-an-underscore 

According to the Google Docs you can alternatively use the reversed Client ID as a redirect URI as well. So if your Client ID is XXXXX.apps.googleusercontent.com you can use com.googleusercontent.apps.XXXXX as your redirect URI. You also need to change the Intern-Filter in your Manifest accordingly.
https://developers.google.com/identity/protocols/OAuth2InstalledApp#creatingcred

**Comment by themelisx** [comment]
This was the problem!
THANK YOU !!!
Make a hint into your documentation about this. It will save hours of searching in similar case.

**Comment by PatrickStoklasa** [comment]
Glad that it worked! Really sorry for the trouble you had. I agree it should be mentioned on the website as well. So far I didn't know that the issue exists but I will definitely add it as soon as possible. Thanks for discovering this!
